bindsym --no-repeat $mod+p exec mpc toggle
bindsym $mod+comma exec mpc prev
bindsym $mod+period exec mpc next
bindsym $mod+j exec mpc seek -5
bindsym $mod+k exec mpc seek +5
bindsym --no-repeat $mod+r exec mpc random
bindsym --no-repeat $mod+s exec mpc single
bindsym --no-repeat XF86AudioPlay exec mpc toggle
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev
bindsym $mod+i exec ~/.config/sway/volume.sh down
bindsym $mod+o exec ~/.config/sway/volume.sh up
bindsym --no-repeat $mod+m exec ~/.config/sway/volume.sh mute
bindsym --no-repeat $mod+v exec ~/.config/sway/wiremix.sh
bindsym --no-repeat $mod+d exec ~/.config/sway/device.sh next
bindsym --no-repeat $mod+Return exec ~/.config/sway/notifications.sh
bindsym --no-repeat $mod+space exec fuzzel
bindsym --no-repeat $mod+Shift+4 exec /bin/bash ~/.config/waybar/euphonica.sh
bindsym --no-repeat $mod+g exec ~/.config/sway/browser.sh
bindsym --no-repeat $mod+u exec ~/.config/sway/bluetooth.sh
bindsym --no-repeat $mod+tab exec foot
bindsym --no-repeat F13 exec ~/.config/sway/cheatsheet.sh
bindsym --no-repeat F11 exec ~/.config/sway/cheatsheet.sh
