bindsym $mod+p exec mpc toggle
bindsym $mod+comma exec mpc prev
bindsym $mod+period exec mpc next
bindsym $mod+j exec mpc seek -5
bindsym $mod+k exec mpc seek +5
bindsym $mod+r exec mpc random
bindsym $mod+s exec mpc single
bindsym XF86AudioPlay exec mpc toggle
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev
bindsym $mod+i exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym $mod+o exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym $mod+m exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym $mod+v exec /home/pi/.config/sway/wiremix.sh
bindsym $mod+d exec /home/pi/.config/sway/notifications.sh
bindsym $mod+space exec fuzzel
bindsym $mod+dollar exec /bin/bash /home/pi/.config/waybar/euphonica.sh
bindsym $mod+tab exec foot
bindsym F13 exec /home/pi/.config/sway/cheatsheet.sh
bindsym F11 exec /home/pi/.config/sway/cheatsheet.sh
