bindsym $mod+p exec mpc toggle
bindsym $mod+comma exec mpc prev
bindsym $mod+period exec mpc next
bindsym $mod+j exec mpc seek -5
bindsym $mod+k exec mpc seek +5
bindsym $mod+r exec mpc random
bindsym $mod+s exec mpc single
bindsym XF86AudioPlay exec mpc toggle
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev
bindsym $mod+i exec ~/.config/sway/volume.sh down
bindsym $mod+o exec ~/.config/sway/volume.sh up
bindsym $mod+m exec ~/.config/sway/volume.sh mute
bindsym $mod+v exec ~/.config/sway/wiremix.sh
bindsym $mod+d exec ~/.config/sway/notifications.sh
bindsym $mod+space exec fuzzel
bindsym $mod+Shift+4 exec /bin/bash ~/.config/waybar/euphonica.sh
bindsym $mod+g exec ~/.config/sway/browser.sh
bindsym $mod+u exec ~/.config/sway/bluetooth.sh
bindsym $mod+tab exec foot
bindsym F13 exec ~/.config/sway/cheatsheet.sh
bindsym F11 exec ~/.config/sway/cheatsheet.sh
